[tool.poetry]
name = "langgraph-rag"
version = "0.1.0"
description = ""
authors = ["ShreyAC962 <shreyAC962@gmail.com>"]
readme = "README.md"
package-mode = true # prevents install errors if README or src layout is missing

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
beautifulsoup4 = "*"
tiktoken = "*"
langchain = "0.2.14"
langchain-community = "0.2.6"
langchainhub = "^0.1.15"
langgraph = "*"
tavily-python = "*"
langchain-openai = "*"
python-dotenv = "*"
black = "*"
isort = "*"
pytest = "*"
langchain-chroma = "*"
langchain-text-splitters = "^1.0.0"
langchain-ollama = "^1.0.0"
langchain-tavily = "^0.2.13"

[tool.poetry.group.dev.dependencies]
black = "^25.11.0"
isort = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"